### ISSUE TITLE
[question] How to get the DACPAC from a project in the solution

### ISSUE THREAD

**Issue by amccool** [nicholasham/SqlLocalDb#2]
What might be a best practice to be able to get the generated dacpac from another project in the same solution so I can use sqllocaldb?

**Comment by glenthomas** [comment]
Something along the lines of...

```
var assembly = <GetYourAssembly>
string filePath = Path.Combine(Path.GetTempPath(), string.Format("{0}.dacpac", Guid.NewGuid()));
FileInfo disk = assembly.GetResource(embeddedPackageFileName).SaveToDisk(filePath);
```

(The dacpac file is an Embedded Resource in the assembly)
